name: expense_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # for date format
  intl: ^0.17.0
  # Service locator
  get_it: ^7.2.0
  # Bloc for state management
  flutter_bloc: ^8.0.0
  # Value equality
  equatable: ^2.0.3
  # Functional programming thingies
  dartz: ^0.10.0
  #http request
  dio: ^4.0.4
  #DI for Theme
  provider: ^6.0.1
  # shimmer
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
