name: expense_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # for date format
  intl: ^0.17.0
  # Service locator
  get_it: ^7.2.0
  # Bloc for state management
  flutter_bloc: ^8.0.0
  # Value equality
  equatable: ^2.0.3
  # Foldable value
  either_dart: ^0.2.0
  #http request
  dio: ^4.0.4
  #DI for Theme
  provider: ^6.0.1
  # shimmer
  shimmer: ^2.0.0
  # Get db path or another path
  path: ^1.8.0
  # Store persistence data
  sqflite: ^2.0.2
  # modal bottomsheet
  modal_bottom_sheet: ^2.1.0
  # api request
  http: ^0.13.5
  # camera
  camera: ^0.10.3
  # uuid
  uuid: ^3.0.7
  # permission_handler
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  assets:
    - assets/
  uses-material-design: true
